tekst_maximumlengte = "Waarschuwing: De langste woorden bevatten MEER DAN 30 karakters."
tekst2_maximumlengte = "Herhaling: de langste woorden bevatten MEER DAN 30 karakters, dit zijn bijgevolg ook moeilijke woorden."
maxlengte_tuple = tekst_maximumlengte,tekst2_maximumlengte,"  "

lijn1_term = "Het aantal kansen dat je krijgt bepaalt de moeilijkheidsgraad."
lijn2_term = "Kies uit alle veelvouden van 2: 2,4,6,8,..."
tuple_moeilijkheidsgraad = lijn1_term,lijn2_term

lijn1 = "eindig programma door stop op eender welk moment te typen."
lijn2 = "herstart door herstart te typen, dan krijg je het woord dat je moest raden ook te zien."
extra_tussen_lijn1_lijn2 = "verander de maximumlengte van de woorden die je wilt raden door {maxlengte} te typen"
lijn3 = "Je mag hoofdletters gebruiken, maar die hebben geen effect."
lijn4 = "Wanneer je een gok wilt doen naar het woord, dan begin je met : en schrijf je daarachter het woord dat je denkt dat het is."
lijn5 = "Bijvoorbeeld: Als je schoen wilt raden, dan typ je {:schoen}."
lijn6 = "De plaatsen van alle overeenkomende karakters worden geprint."
lijn7 = "Iedere underscore betekent een karakter of spatie die nog niet geraden is."
lijn8 = "De woorden zijn zowel afkomstig uit het alledaagse leven als uit het ICT domein."
lijn9 = "Andere specifieke domeinen komen niet aan bod."
lijn10 = "De woorden kunnen zowel makkelijk als moeilijk zijn."
lijn11 = "Alle woorden die trema's of accenten bevatten zijn inbegrepen."
lijn12 = "Houd er rekening mee dat die geraden moeten worden zonder de accenten."
lijn13 = "Opmerking: Hoe snel de tekst wordt geprint is omgekeerd evenredig met hoe aandachtig je de tekst zou moeten lezen. "
lijn14 = "Dit werd echter enkel in de mate van het mogelijke gerealiseerd."
lijn15 = "m.a.w. De tekst die aandachtig gelezen moet worden verschijnd trager dan de tekst waar er diagonaal door gelezen mag worden."
lijn16 = "Zowel bij winst als bij verlies wordt er een liedje afgespeeld."
lijn17 = "Sommige woorden zijn overigens afkomstig uit Nederland of worden hoofdzakelijk gebruikt in Nederland."
lijn18 = "De woorden kunnen vervoegingen van werkwoorden bevatten."
algemene_info_verzameling = lijn1,extra_tussen_lijn1_lijn2,lijn2,"  ",lijn3,lijn4,lijn5,"  ",lijn6,lijn7,"  ", lijn8,lijn9, lijn10, lijn11, lijn12,"  ", lijn13, lijn14,lijn15, lijn16,"  ", lijn17, lijn18
